### ISSUE TITLE
contour direction is not correct

### ISSUE THREAD

**Issue by typemytype** [fonttools/skia-pathops#10] opened 2017-11-13 12:18 UTC
The first drawing the source, second the result through skia, the third with booleanOperations

![screen shot 2017-11-13 at 13 16 00](https://user-images.githubusercontent.com/1190358/32725323-e2dbe594-c874-11e7-8e93-470ddf93e65f.png)

```glif
<?xml version="1.0" encoding="UTF-8"?>
<glyph name="B" format="2">
  <outline>
    <contour>
      <point x="375" y="24" type="curve" smooth="yes"/>
      <point x="567" y="24"/>
      <point x="723" y="180"/>
      <point x="723" y="372" type="curve" smooth="yes"/>
      <point x="723" y="563"/>
      <point x="567" y="719"/>
      <point x="375" y="719" type="curve" smooth="yes"/>
      <point x="184" y="719"/>
      <point x="28" y="563"/>
      <point x="28" y="372" type="curve" smooth="yes"/>
      <point x="28" y="180"/>
      <point x="184" y="24"/>
    </contour>
    <contour>
      <point x="375" y="147" type="curve" smooth="yes"/>
      <point x="252" y="147"/>
      <point x="151" y="248"/>
      <point x="151" y="372" type="curve" smooth="yes"/>
      <point x="151" y="495"/>
      <point x="252" y="595"/>
      <point x="375" y="595" type="curve" smooth="yes"/>
      <point x="499" y="595"/>
      <point x="599" y="495"/>
      <point x="599" y="372" type="curve" smooth="yes"/>
      <point x="599" y="248"/>
      <point x="499" y="147"/>
    </contour>
    <contour>
      <point x="175" y="180" type="line"/>
      <point x="232" y="120" type="line"/>
      <point x="386" y="226" type="line"/>
      <point x="805" y="-96" type="line"/>
      <point x="918" y="-22" type="line"/>
      <point x="379" y="332" type="line"/>
    </contour>
  </outline>
</glyph>
```

**Comment by anthrotype** [comment] 2017-11-13 12:22
yeah, the handling of contour direction in the resulting path sometimes is completely wrong, I still haven't figured out why. I have to say I've lost must of my initial enthusiasm.
I'm not looking forward to fix skia bugs.

**Comment by khaledhosny** [comment] 2017-11-13 16:57
@anthrotype If you think Skia is not suitable for our needs, we better kill this experiment now and start over with something else.

**Comment by anthrotype** [comment] 2017-11-13 17:01
I don't know, Khaled. Maybe we are using the API incorrectly... I need help from you guys debugging this.
I can expose more SkPath methods to Python to help debugging, but I don't know if I have the ability/time to dig deeper in the C++ implementation.

**Comment by adrientetar** [comment] 2017-11-13 17:04
It's fine, we just need to shift the start point to the next on curve and reverse each contour in the resulting path.

**Comment by anthrotype** [comment] 2017-11-13 17:15
We can also try reproducing the issue using this interactive page https://fiddle.skia.org/c/@pathops
you can write some C++ code that uses skia and see the rendering live.
If we can repro then we can file a bug and hope they fix it upstream.

**Comment by adrientetar** [comment] 2017-11-13 17:18
It's not a bug: https://groups.google.com/d/msg/skia-discuss/9xieDIhMoxk/XbfbmHOTAAAJ

But the transform to what we want is (afaict) deterministic.

**Comment by anthrotype** [comment] 2017-11-13 17:24
so if skia cannot give us a result path with nonzero winding fill type, but always returns a path with even-odd fill type, then we would need a reliable way to change it back to non-zero winding...

**Comment by adrientetar** [comment] 2017-11-13 17:30
Actually yeah, with the example of the OP it doesn't work, one contour needs not be reverse.

**Comment by khaledhosny** [comment] 2017-11-13 17:30
Can someone give me a python snippet that I can test with?

**Comment by adrientetar** [comment] 2017-11-13 17:31
Anyway yeah assuming it's a valid even odd contour (which I assume it is, for proper rendering) there must be an algorithm to change the contour according to the other fill rule.

**Comment by anthrotype** [comment] 2017-11-13 17:33
in TruFont, you can do

```python
from pathops import *
glyph = CurrentGlyph()
contours = list(glyph)
glyph.clearContours()
union(contours, glyph.getPen())
```

**Comment by anthrotype** [comment] 2017-11-13 17:35
note that the `union` function is internally calling the binary `Op` function with a UNION operator and and the second operand being another empty Path.

You could alternatively try using a OpBuilder instance (wrapper for SkOpBuilder.cpp), call add methods on it, and then finally the resolve method, to see if anything changes.

And I noticed sometimes one gets it right, while the other doesn't. I still haven't understood the difference between the two though.

**Comment by adrientetar** [comment] 2017-11-13 17:39
Seems converting from even odd to winding might be quite complex. @behdad thoughts?

**Comment by anthrotype** [comment] 2017-11-13 17:40
also, in the functions defined in `operations.py` module, we are accumulating multiple contours in a single Path, and pass that to Op function as a whole.

We could alternatively try calling builder.add for as many contours in a glyph and see if that changes the result. In my tests, it didn't help much (some inner contours would even disappear altogether!)

**Comment by khaledhosny** [comment] 2017-11-13 18:05
Interestingly, Skia’s canvas is able to draw the glyph correctly after the union operation https://fiddle.skia.org/c/4873ecb267c61ff616953a3b3887ad9e

**Comment by anthrotype** [comment] 2017-11-13 18:31
@khaledhosny yeah, because it's probably filling them with even-odd rule.

**Comment by behdad** [comment] 2017-11-13 19:15
> Seems converting from even odd to winding might be quite complex. @behdad thoughts?

Not more complex than doing it with outlines with overlaps!  We should ask if Skia has that already. If not, something along https://github.com/behdad/glyphy/blob/master/src/glyphy-outline.cc#L268

**Comment by typemytype** [comment] 2017-11-14 08:57
its seems like `fix_winding` is solving lots of issues...

**Comment by typemytype** [comment] 2017-11-14 09:16
but still finding issues

![screen shot 2017-11-14 at 10 15 54](https://user-images.githubusercontent.com/1190358/32771999-d397baee-c924-11e7-854b-109b06f1bcee.png)

(and some other I cannot share publicly without asking permission first)

**Comment by adrientetar** [comment] 2017-11-14 10:14
I think FixWinding is written for single contour paths (it's called by the builder on final paths being finally merging them), which is why it can have weird results for multiple contours.

**Comment by adrientetar** [comment] 2017-11-14 23:44
What we could try is:

Draw one contour on another SkPath (iterate until next moveTo) -> call FixWinding on that SkPath -> draw it in outPen and clear

**Comment by anthrotype** [comment] 2017-11-15 11:42
The core developer of Skia, Cary Clark is willing to help but he first want us to write down the requirements:
https://groups.google.com/d/msg/skia-discuss/9xieDIhMoxk/NlQq-AfQBAAJ

we need to reply to him

**Comment by typemytype** [comment] 2017-11-15 13:24
I can list where booleanOperations interferes with the contours and how it handles different situation. what is the structure of such a requirements? meaning how to write that down?

**Comment by anthrotype** [comment] 2017-11-15 13:30
not sure. he mentions writing up some sample code using http://fiddle.skia.org/ (so it's easy to visualize and we can just share a link) with the desired outcome.
he's also would like to see how we're using the API.
Maybe it'd be easier to just arrange a hangout with him? @behdad

**Comment by adrientetar** [comment] 2017-11-16 13:23
The requirements: to preserve contour direction and start points as much as possible (when the contours are modified and when they aren't).

Also we ought to provide sample results. @typemytype Do you have other boolean ops inputs you can share? The Q in the first post is a good one.

We should have inputs and the results of booleanOperations in SkPath form, i.e. make a path and then call path.dump(). That will print the c++ repr (like I did [here](https://groups.google.com/d/msg/skia-discuss/9xieDIhMoxk/ZEFUbx_LAAAJ)).

**Comment by behdad** [comment] 2017-12-10 22:51
Have we got back to Cary on this?

**Comment by adrientetar** [comment] 2017-12-10 23:16
No, someone ought to do it.

**Comment by adrientetar** [comment] 2018-05-01 18:56
As an update, I responded in the thread a while ago and bungeman@ pointed to [this skia bug](https://bugs.chromium.org/p/skia/issues/detail?id=7682) about having pathops output proper winding paths (assigned to Cary Clark).

**Comment by anthrotype** [comment] 2018-08-08 19:11
@typemytype @adrientetar @khaledhosny can you retry with the latest skia-pathops (v0.1.3) and see if it fixes the issue with winding direction?
There should be wheels available from PyPI shortly (if all the builds complete).

**Comment by adrientetar** [comment] 2018-08-08 23:15
Yes it seems correct now, nice work! I guess the only remaining issue now is the jumping start points.

**Comment by anthrotype** [comment] 2018-08-09 10:34
> Yes it seems correct now, nice work!

Yay!

> I guess the only remaining issue now is the jumping start points

I'll work on fixing #9 now

**Closed** 2018-08-09 10:34 UTC

**Comment by anthrotype** [comment] 2018-08-17 17:35
https://bugs.chromium.org/p/skia/issues/detail?id=7682

they just added a new `SkPathOps::AsWinding` function to convert SkPath from even odd fill to non-zero winding. I'll see if it fixes this bug and if so I'll remove my own `winding_from_even_odd` function.

**Comment by typemytype** [comment] 2018-08-20 08:34
I dont know why, but pathops slowed down a lot... (more correct but a lot slower)

**Comment by anthrotype** [comment] 2018-08-20 17:17
I didn’t notice that. Since what version? How much slower? I’ll take a look after I’m back in September.

**Comment by yisibl** [comment] 2026-05-25 17:53
> They seem to have forgotten a stray debug print statement so now we get loads of "incomplete!"...

It looks like the code `SkDebugf("incomplete...` has been removed from Skia. Maybe you could try it again?
